---
- name: Create /etc/passwd file with root ownership and 0600 permissions
  hosts: all
  become: yes
  become_method: dzdo

  tasks:
    - name: Create /etc/passwd file
      ansible.builtin.file:
        path: /etc/passwd
        state: touch
        mode: '0600'
        owner: root
        group: root
