---
- name: Set motd on Linux systems
  hosts: all
  become: yes
  become_method: dzdo
  
  tasks:
    - name: Template a file to /etc/motd
      ansible.builtin.template:
        src: /files/eula.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
        
#    - name: "copy motd file to /etc/motd"
#      copy:
#        src: files/eula.j2
#        dest: /etc/motd
#        owner: root
#        group: root
#        mode: '644'
